[project]
name = "wisharify"
version = "0.1.0"
description = "Simple qr code generator for wifi connection sharing"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "keyring>=25.6.0",
    "pillow>=11.1.0",
    "qrcode>=8.0",
]
